name: Rebase

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 0 * * *'

env:
  CI: true

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: rebase on original
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch --unshallow
          git remote add orig https://github.com/typed-ember/glint.git          
          git fetch --all
          git pull orig main --rebase
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Locate Yarn Cache
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test
      - name: push
        run: |
          git checkout -b rebase-orig
          git push origin/rebase-orig
      - name: create pr
        run: gh pr create -B main -H rebase-orig --title 'rebase' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        
        
